### ISSUE TITLE
It is better for the peer with the smallest lag(fall behind index) to become the transferee.

### ISSUE THREAD

**Issue by XiaoyiPeng** [openmessaging/dledger#111]
Hi, @RongtongJin 

In method `DLedgerServer#checkPreferredLeader()`, The first peer in the list `preferredLeaderIds  `that meets the condition is determined to be the leader transferee, as show below： 
![image](https://user-images.githubusercontent.com/8653312/155258461-93a9eede-9276-44e0-96ce-dc37452af25d.png)

I think, the peer with the smallest lag(fall behind index) be the `transferee`, which may be better.

**Comment by RongtongJin** [comment]
Merged
