### ISSUE TITLE
High CPU usage in EntryDispatcher

### ISSUE THREAD

**Issue by yuz10** [openmessaging/dledger#122]
when no any message is produced,  dledger use 200% CPU, in EntryDispatcher.doWork
![image](https://user-images.githubusercontent.com/14816818/160864353-b80ff1fd-51b4-4684-a135-229b1aedff50.png)

![image](https://user-images.githubusercontent.com/14816818/160862030-d1a2c891-04cc-4d89-88e8-1e3cb948a9f6.png)

link #98

**Comment by RongtongJin** [comment]
Merged
