### ISSUE TITLE
hanged unavailable file in deleteExpiredFileByTime

### ISSUE THREAD

**Issue by yuz10** [openmessaging/dledger#125]
the first file of dataFileList is not available, after deleteExpiredFileByTime.
![image](https://user-images.githubusercontent.com/14816818/162203217-fe34b9ea-1c64-4828-88af-8c9d146f56a1.png)

![image](https://user-images.githubusercontent.com/14816818/162203357-ef2c43e3-1d3b-48b7-a268-48d01954851d.png)

the first time shutdown() is called, if refCount > 0, the file will not be deleted and mark available = false.
the second time shutdown() is called, it will be deleted. but if the disk is not full the second time,  shutdown() is not called, and the file will be not available all the time.

see https://github.com/apache/rocketmq/blob/develop/store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java#L1690

**Comment by RongtongJin** [comment]
Merged
