### ISSUE TITLE
[2022 Alibaba Summer of Code] Support Snapshot for DLedger

### ISSUE THREAD

**Issue by RongtongJin** [openmessaging/dledger#131]
# 2022 Alibaba Summer of Code

Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻
Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship
- Get your code adopted and used by the open source project！
## Timeline

 ![](https://s1.ax1x.com/2022/05/25/XFXxC6.png)

## Our Mentor

@RongtongJin jinrongtong@apache.org @tsunghanjacktsai tsaitsunghan@apache.org

## Subject

Snapshot is a very important feature for raft protocol. For example, it can greatly shorten the recovery time and delete useless logs in time. Currently, DLedger has not implemented this feature.

@hzh0425 has implemented statemachine feature and the snapshot interface is left. 

https://github.com/openmessaging/dledger/blob/4293093354d8b1464ce567fcaba9d3999e37e4b4/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java#L37-L52

Welcome to implement snapshot feature for dledger on this basis and improve the log deletion strategy in state machine mode

## difficulty

Advanced (10000 Yuan)

## Apply Now

Upload your CV and project proposal via ASOC 2022 official website：
https://opensource.alibaba.com/asoc2022

If you have any questions, visit the event website:https://opensource.alibaba.com/asoc2022

Email address: [opensource@alibaba-inc.com](mailto:opensource@alibaba-inc.com)

**Comment by RongtongJin** [comment]
> Snapshot is a very important feature for raft protocol. For example, it can greatly shorten the recovery time and delete useless logs in time. Currently, DLedger has not implemented this feature.
> 
> In the [statemachine](https://github.com/openmessaging/dledger/tree/statemachine) branch, @hzh0425 has implemented statemachine feature and the snapshot interface is left.
> 
> https://github.com/openmessaging/dledger/blob/4293093354d8b1464ce567fcaba9d3999e37e4b4/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java#L37-L52
> 
> Welcome to implement snapshot feature for dledger on this basis

**Comment by yanchaomei** [comment]
Hi, I want to take over this issue.

**Comment by hzh0425** [comment]
> Hi, I want to take over this issue.

Welcome, you can write an rfc to illustrate your ideas

**Comment by ravig-kant** [comment]
> Hi, I want to take over this issue.

I also wish to contribute to this issue. Can we work on it together?

**Comment by RongtongJin** [comment]
> > Hi, I want to take over this issue.
> 
> I also wish to contribute to this issue. Can we work on it together?

Of course.

**Comment by RongtongJin** [comment]
I have put this issue to ASoC. Welcome to apply for this subject!

**Comment by TheR1sing3un** [comment]
> I have put this issue to ASoC. Welcome to apply for this subject!

Hello, does anyone have been doing this project? I am also more interested in this.

**Comment by RongtongJin** [comment]
> > I have put this issue to ASoC. Welcome to apply for this subject!
> 
> Hello, does anyone have been doing this project? I am also more interested in this.

Not yet. Welcome to write an rfc to illustrate your ideas.

**Comment by dxlog0** [comment]
Today is 5.30(The day that "open for application" in timeline),
but the link:https://opensource.alibaba.com/asoc2022, when I click the link, it redirects to error.taobao.com

Did anyone else met that problem too?

(By the way, I've sent a e-mail about my idea to jinrongtong@apache.org)

**Comment by dxlog0** [comment]
> Today is 5.30(The day that "open for application" in timeline), but the link:https://opensource.alibaba.com/asoc2022, when I click the link, it redirects to error.taobao.com
> 
> Did anyone else met that problem too?
> 
> (By the way, I've sent a e-mail about my idea to [jinrongtong@apache.org](mailto:jinrongtong@apache.org))

Now, it's available!

**Comment by yyt86** [comment]
Same question here. How many people have applied for this project?
