### ISSUE TITLE
Dledger properties configuration file Support

### ISSUE THREAD

**Issue by mxsm** [openmessaging/dledger#171]
Deleger configuration using the encoding, should support configuration file configuration。The **DLedgerConfig** config class should can config in properties config file.

**Comment by mxsm** [comment]
for example, dataStorePath we can config in properties file.
```
dataStorePath=/root/path/mxsm
```

**Comment by mxsm** [comment]
### sample
dledger.properties 
```properties
group=dleger
peers=n0-localhost:20911
```

how to use

```
java -jar target/DLedger.jar server -c /tmp/config/dledger.properties
```

**Comment by TheR1sing3un** [comment]
Hi~ Maybe we have done the same work.
In this pr, it supports configuration(yaml). https://github.com/openmessaging/dledger/pull/150/commits
And I build it basing Multi-Raft structure. https://github.com/openmessaging/dledger/issues/82
https://github.com/openmessaging/dledger/pull/150/commits
Could we talk about this? 😂

**Comment by TheR1sing3un** [comment]
Hi~ Maybe we have done the same work.
In this pr, it supports configuration(yaml). 
https://github.com/openmessaging/dledger/pull/150/commits
And I build it basing Multi-Raft structure. 
https://github.com/openmessaging/dledger/issues/82
Could we talk about this? 😂

**Comment by mxsm** [comment]
> Hi~ Maybe we have done the same work. In this pr, it supports configuration(yaml). https://github.com/openmessaging/dledger/pull/150/commits And I build it basing Multi-Raft structure. #82 Could we talk about this? 😂

I watched the RP, when you pr be merged,I'll build on this for other feature development.

**Comment by TheR1sing3un** [comment]
> > Hi~ Maybe we have done the same work. In this pr, it supports configuration(yaml). https://github.com/openmessaging/dledger/pull/150/commits And I build it basing Multi-Raft structure. #82 Could we talk about this? 😂
> 
> I watched the RP, when you pr be merged,I'll build on this for other feature development.

ok~looks great
