### ISSUE TITLE
Unable to Start DLedger without config.yaml

### ISSUE THREAD

**Issue by tsunghanjacktsai** [openmessaging/dledger#210]
After supporting multi-raft mode (#150 ), DLedger should be able to start with the DLedgerConfig under the normal mode and DLedgerProxyConfig under the multi-raft mode.

However, DLedger can only boot after providing a config.yaml and --config in the command line at the moment, which means that users are forced to use multi-raft mode to start it. It supposed to support both modes (original one & multi-raft) after this upgrade.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/34185019/187827537-83bce16e-563c-45b4-90cb-8b635152b034.png">

**Comment by TheR1sing3un** [comment]
I fix that problem yesterday, please have a try in now master branch~
