### ISSUE TITLE
Fix wrong recover logic after reseting offset

### ISSUE THREAD

**Issue by TheR1sing3un** [openmessaging/dledger#245]
## 快照时resetOffset之后的mmap文件在重启恢复时的起始entry定位错误问题
> 考虑如下情况

- Mmap 文件大小为1M (1024B)
- 一个日志消息体为512B
- 一个完整的日志Entry大小为512 + 48 = 560B

![](https://cdn.nlark.com/yuque/0/2022/jpeg/22446956/1665651932489-2ddbeb66-5b60-4e12-a55d-3c62322f7fa6.jpeg)
此时已经append了两条日志进来，假设此时触发了快照条件，那么需要生成状态机快照，并将日志0和1都删除掉。也就是调用dataFileList的resetOffset方法，重置到postion为1584的位置。
![image.png](https://cdn.nlark.com/yuque/0/2022/png/22446956/1665651601723-a85115fd-2de7-454b-93e4-c98d6f11ddb0.png#clientId=u0ea67ad4-6db1-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=396&id=uf3974a13&margin=%5Bobject%20Object%5D&name=image.png&originHeight=396&originWidth=1110&originalType=binary&ratio=1&rotation=0&showTitle=false&size=70048&status=done&style=none&taskId=u2d54b4b3-13a2-41f1-b531-a754ebc60de&title=&width=1110)
实际也就是将Mmap1的文件的startPosition更新为560，表示当前这个MmapFIle从560开始有效。
![image.png](https://cdn.nlark.com/yuque/0/2022/png/22446956/1665651717564-d6351e7a-5afe-4db8-b15b-8134102c18bf.png#clientId=u0ea67ad4-6db1-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=980&id=u4bdbfa0d&margin=%5Bobject%20Object%5D&name=image.png&originHeight=980&originWidth=1320&originalType=binary&ratio=1&rotation=0&showTitle=false&size=143761&status=done&style=none&taskId=u96f210da-8b3d-4de7-8f8e-6294b3393dd&title=&width=1320)
那么其实这里并没有真正的删除这个index1的日志，只是一个逻辑删除的操作，让之后的日志从560以后开始append。但是这个startPostion是在内存中的，重启就没有了，也就引出了后面的问题。
> reset后的Mmap文件

![](https://cdn.nlark.com/yuque/0/2022/jpeg/22446956/1665651913869-2f881196-187e-4464-bef1-e644c7f6b5ec.jpeg)
假设此时重启，进入到`DefaultMmapFileStore#recover`的流程。
![image.png](https://cdn.nlark.com/yuque/0/2022/png/22446956/1665652003800-1ac6de95-5c94-4690-a9bc-58407fcf1c2c.png#clientId=u0ea67ad4-6db1-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=1784&id=u70552040&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1784&originWidth=2548&originalType=binary&ratio=1&rotation=0&showTitle=false&size=528009&status=done&style=none&taskId=uafb3ea8b-e292-4249-836f-8768104794f&title=&width=2548)
此时也就是直接从第一个文件开始恢复，由于我们之前是逻辑删除的，导致实际上entry1还存在，indexFile中也是同理，那么其实我们也逻辑上恢复了一个之前已经删除掉的entry1。
### 解决方案
如果持久化startPosition的话，比较复杂，可能需要对于存储的entry结构进行更改，新增一个8字节的字段，比较繁琐，而且其实只有第一个MmapFile需要使用到这个字段，所以我们可以直接在resetOffset的时候，之前将该文件中offset之前的数据删除，比如说用Blank覆盖占位。
![](https://cdn.nlark.com/yuque/0/2022/jpeg/22446956/1665653086616-36835c54-4e3c-4df1-878b-2a229cc3a544.jpeg)
然后在recover的时候，直接针对这种情况进行处理，比如说直接跳过第一个文件的起始blank，并且此时可以更新startPosition，如果检测到该文件后续也都是blank，那么可以直接删除该文件，然后从第二个文件开始处理。

**Comment by akkw** [comment]
能否将此信息持久化到快照的元数据文件解决此问题呢

**Comment by TheR1sing3un** [comment]
> 能否将此信息持久化到快照的元数据文件解决此问题呢

这也是一种解决方法，不过这个主要出现的情况是resetoffset导致的，快照是引起resetoffset的一个原因，我感觉持久化到快照的元数据中可能不算一个通用的解决方法？

**Comment by akkw** [comment]
其实这里好像并不用关注他的startOffset，因为raft的log 是append，其次做好快照之后通过快照恢复也不会恢复出历史数据，只是日志文件中的日志多存了一段历史数据，如果需要通过快照+日志的方式恢复数据也可以通过快照的元数据文件找到上次快照的最后一个offset，接着再从日志恢复数据
如果是下次快照保存快照也是从内存中的最新数据保存，不会涉及到未删除的老的日志
所以我理解多保存的这段日志似乎没什么影响

**Comment by akkw** [comment]
> 其实这里好像并不用关注他的startOffset，因为raft的log 是append，其次做好快照之后通过快照恢复也不会恢复出历史数据，只是日志文件中的日志多存了一段历史数据，如果需要通过快照+日志的方式恢复数据也可以通过快照的元数据文件找到上次快照的最后一个offset，接着再从日志恢复数据 如果是下次快照保存快照也是从内存中的最新数据保存，不会涉及到未删除的老的日志 所以我理解多保存的这段日志似乎没什么影响

如果填充的话反而会导致做快照时的性能问题
