### ISSUE TITLE
Preferred Leader leads to node unavailability problem

### ISSUE THREAD

**Issue by Git-Yang** [openmessaging/dledger#85]
**The initial state of the broker group**
n0 is master, preferredLeader
n1 and n2 is slave

**The status after the re-election is as follows**
n0 and n2 is slave
n1 is master

**Problem Description**
n0 node cannot synchronize data.
![image](https://user-images.githubusercontent.com/30995057/126924877-db20ef60-f4e1-4e99-a8e4-1444505b538d.png)
If the cluster restarts, the brokerId is always -1.
![image](https://user-images.githubusercontent.com/30995057/126925531-5fb87087-a15d-4303-a398-970a2c5b9197.png)

**Problem Analysis**
When the preferredLeader is triggered to re-initiate the election, if the ldeger entry index lags behind the leader node, the vote fails. 
As the term increases by 1, the node is always larger than the other node's term and cannot be re-elected as a follower. Therefore, the preferredLeader will always be in the candidate state, resulting in the node being unavailable.

**The log of the n0 node is as follows**
![image](https://user-images.githubusercontent.com/30995057/126926889-692d6dea-4e3c-47a8-979a-a56baaa9909c.png)

**The log of the n1 node is as follows**
![image](https://user-images.githubusercontent.com/30995057/126926954-f8bbb4b0-ab3b-4a7e-b8af-1a74aa1a20aa.png)

**Comment by Git-Yang** [comment]
**Optimization ideas**
**The first optimization scheme**: When the leader receives the heartbeat response, if the response term is greater than the current term, it re-enters the Candidate to initiate the next round of voting.
**Shortcomings**: May trigger multiple re-elections.

**Comment by Git-Yang** [comment]
@vongosling Can you help me review this revision?

**Comment by Git-Yang** [comment]
**Optimization ideas**
The second optimization scheme: 
- Mark the unavailable state of the node in the voting phase.
- When receiving the heartbeat of the leader node, if the node status is unavailable, try to recover.

**Comment by maixiaohai** [comment]
@RongtongJin this change may not a good choice, can you help to review it. This problem will cause the unavailable of node of broker group.

**Comment by Cczzzz** [comment]
I think ,if preferred leader is too much behind。Should be downgraded follower

**Comment by Git-Yang** [comment]
> I think ,if preferred leader is too much behind。Should be downgraded follower

After downgrading to follower, the voting term is still larger than other nodes. Therefore, the term will be rolled back first and then the node will be downgraded to follower.

**Comment by Git-Yang** [comment]
@RongtongJin Please help to review it, and I am very much looking forward to other better optimization methods that may be communicated together.

**Comment by RongtongJin** [comment]
Merged
