### ISSUE TITLE
Unable to push data problem

### ISSUE THREAD

**Issue by Git-Yang** [openmessaging/dledger#87]
**Problem Description**
- After the cluster is started, a follower node in the Broker group is unavailable. 
- After the node was restored, it was found that the data could not be synchronized.
![image](https://user-images.githubusercontent.com/30995057/127302188-2c3e0e02-531f-481c-b16a-fe1e71723b3b.png)

**Problem Analysis**
- After the cluster is started, a follower node in the Broker group is unavailable.
- When the n1 node is restored, the message that the leader node pushes to the n1 node has expired.
- At this time, the leader node cannot obtain the message to be pushed and throws an exception.
![image](https://user-images.githubusercontent.com/30995057/127303848-63736203-8f1a-4c19-914e-d14aabbeff04.png)

**Code Analysis**
- When the entry corresponding to writeIndex does not exist, an exception is thrown.
- Capture and print the exception information in doWork, and then execute append again.
![image](https://user-images.githubusercontent.com/30995057/127304730-c9ab02e3-450b-4d7f-97eb-55da61de0630.png)
![image](https://user-images.githubusercontent.com/30995057/127304855-1afadaae-24be-495e-8d94-49dcdc8087bf.png)

**Comment by RongtongJin** [comment]
Merged
