### ISSUE TITLE
 single/batch pushes are not compatible with each other

### ISSUE THREAD

**Issue by Git-Yang** [openmessaging/dledger#94]
**Background**
The online service is a single push, and now I want to upgrade to batch push.
When the configuration of the leader node and the follower node is inconsistent with batch push, the data cannot be pushed.

**optimization**
Compatible with master and follower Synchronize data when the batch push configuration is inconsistent.
- leader: enableBatchPush=true &  follwer: enableBatchPush=false
- leader: enableBatchPush=false & follwer: enableBatchPush=true

**Comment by RongtongJin** [comment]
Merged
